version: "3"

networks:
    default:
        external:
            name: gateway

services:
    code-server:
        image: codercom/code-server:latest
        command:
            - --allow-http
            - --password=${PASSWORD}
        volumes:
            - ${DATA_DIR}/coder:/home/coder
        labels:
            - traefik.enable=true
            - traefik.docker.network=gateway
            - traefik.frontend.rule=Host:text.southcla.ws
            - traefik.frontend.headers.SSLRedirect=true
            - traefik.frontend.headers.SSLHost=text.southcla.ws
            - traefik.frontend.redirect.regex=^https?://[a-z0-9.]+/(.*)
            - traefik.frontend.redirect.replacement=https://text.southcla.ws/$${1}
            - traefik.port=8443
